name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    strategy:
      matrix:
        project: ['frontend', 'backend']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: ${{ matrix.project }}/package-lock.json

    - name: Install dependencies
      run: |
        cd ${{ matrix.project }}
        npm ci

    - name: Run tests
      run: |
        cd ${{ matrix.project }}
        npm test -- --coverage
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/test_db
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - name: Run linter
      run: |
        cd ${{ matrix.project }}
        npm run lint

  security-check:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run dependency audit
      run: |
        cd frontend && npm audit
        cd ../backend && npm audit

    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v2