name: Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t frontend:latest -f Dockerfile.frontend .
        docker build -t backend:latest -f Dockerfile.backend .
        docker tag frontend:latest ${{ secrets.DOCKER_REGISTRY }}/frontend:$GITHUB_SHA
        docker tag backend:latest ${{ secrets.DOCKER_REGISTRY }}/backend:$GITHUB_SHA
        docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:$GITHUB_SHA
        docker push ${{ secrets.DOCKER_REGISTRY }}/backend:$GITHUB_SHA

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
        service: crime-reporting-service
        cluster: crime-reporting-cluster
        wait-for-service-stability: true